default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: cloud_run_sample_rails_app_development
  host: <%= ENV['PG_HOST_DEVELOPMENT'] || 'localhost' %>
  port: <%= ENV['PG_PORT_DEVELOPMENT'] || 5432 %>
  username: <%= ENV['PG_USER_DEVELOPMENT'] || 'root' %>
  password: <%= ENV['PG_PASS_DEVELOPMENT'] || 'postgres' %>

test:
  <<: *default
  database: cloud_run_sample_rails_app_test
  host: <%= ENV['PG_HOST_TEST'] || 'localhost' %>
  port: <%= ENV['PG_PORT_TEST'] || 5432 %>
  username: <%= ENV['PG_USER_TEST'] %>
  password: <%= ENV['PG_PASS_TEST'] %>

production:
  <<: *default
  database: cloud_run_sample_rails_app_production
  host: <%= ENV['PG_HOST_PRODUCTION'] || 'localhost' %>
  port: <%= ENV['PG_PORT_PRODUCTION'] || 5432 %>
  socket: <%= ENV['PG_SOCKET_PRODUCTION'] || '/cloudsql/potch-general:us-central1:potch-postgresql-main' %>
  username: <%= ENV['PG_USER_PRODUCTION'] %>
  password: <%= ENV['PG_PASS_PRODUCTION'] %>
